# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthome',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b'post_images'),
        ),
    ]
